### ISSUE TITLE
`React/RCTBundleURLProvider.h` file not found. 

### ISSUE THREAD

**Issue by ChristianTucker** [invertase/react-native-firebase-starter#1]
Steps to reproduce:

1.  Clone the repository
2.  Run npm install
3.  Run pod install
4.  Add .plist file from Firebase
5.  Open .xcodeworkspace file
6.  Archive the application
7.  Error

**Comment by chrisbianca** [comment]
Is this still a problem?

**Comment by cagataycali** [comment]
I faced this issue today, and I fixed with this stackoverflow answer: https://stackoverflow.com/a/44039891

**Comment by cagataycali** [comment]
But @chrisbianca you must be downgrade React native version to 0.51.0 cause this: https://github.com/facebook/react-native/issues/17618

React native debugger is not working properly in 0.52.0.

Respects.
