### ISSUE TITLE
Program type already present: io.invertase.firebase.database.RNFirebaseDatabase$7

### ISSUE THREAD

**Issue by denizbas92** [invertase/react-native-firebase-starter#102]
"react-native": "0.58.5",
"react-native-firebase": "5.2.2",

I cloned this react-native-firebase-starter and I started working on it. When I try to get apk file for android, the error as shown above appears and I could not get apk file. Is there any solution ?

**Comment by uguraktas** [comment]
I have same problem but for admob

**Comment by Riyaz619** [comment]
did you use react-native link command?

Faced the same problem rebuild the project from the starter package again and still got the same error, On multiple trials found that using react-native link is causing this problem couldn't figure out how to solve this but you can avoid using react-native link command if you have some libraries to link to project link them individually.

**Comment by denizbas92** [comment]
> I have same problem but for admob

Did you find any solution ?

**Comment by hindsricardo** [comment]
Can someone please answer this

**Comment by pedro-lb** [comment]
We had the same problem, but for admob. Didn't find any solution.

In our case we were trying to use [React Native Push Notifications](https://github.com/zo0r/react-native-push-notification) along with React Native Firebase.

We ended up using the Firebase notification method, because we couldn't install the other package.

**Comment by mikehardy** [comment]
I believe this is a gradle cache issue actually

https://github.com/invertase/react-native-firebase/issues/1859#issuecomment-506624299
