### ISSUE TITLE
[Firebase/Core][I-COR000005] No app has been configured yet.

### ISSUE THREAD

**Issue by TheSavior** [invertase/react-native-firebase-starter#106]
When following the instructions in the getting started my app loads, but I'm not able to anonymously authenticate in JS. 

I uncommented these lines from the starter (and rearranged it to not use await)
```
firebase.auth().signInAnonymously().then(({user}) => {
      console.warn('User -> ', user.toJSON());
    });
```

and I get this error:

![Simulator Screen Shot - iPhone XS - 2019-04-11 at 22 43 17](https://user-images.githubusercontent.com/249164/56014710-392e2800-5cab-11e9-99b8-4249f72e5e43.png)

It looks like it is related to the build warnings in xcode:

```
2019-04-11 22:32:59.867587-0700 DailyTracker[59238:884395] 5.20.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
2019-04-11 22:32:59.909820-0700 DailyTracker[59238:884395] 5.20.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
```

I believe I followed the [getting started instructions](https://rnfirebase.io/docs/v5.x.x/installation/basic-kit#Getting-Started) completely (although clearly not haha). Specifically I imagine this is part of these instructions:

```
3.1) [iOS] Follow the add firebase to your app instructions here to generate your GoogleService-Info.plist file if you haven't done so already - use the package name generated previously as your iOS bundle ID.
3.2) [iOS] Place this file in the ios/ directory of your project.
```

I went through that set up and copied `GoogleService-Info.plist` into my ios directory:
```

$ ls -lah ios
.
..
DailyTracker
DailyTracker-tvOS
DailyTracker-tvOSTests
DailyTracker.xcodeproj
DailyTracker.xcworkspace
DailyTrackerTests
GoogleService-Info.plist
Podfile
Podfile.lock
Pods
build
```

And then did the build through xcode to get the warnings above. 

What step am I missing here? Is the starter template or instructions missing some set up?

**Comment by Salakar** [comment]
Hey again @TheSavior 👋

I think I see the problem, it's a fairly common thing so no worries; adding the plist file via finder doesn't link it in Xcode annoyingly, you'll need to also add it via the Xcode UI (right click project > add files)

I'm actually adding a better warning for this in the next major version so hopefully this will help others coming across this 🙈

**Comment by TheSavior** [comment]
Hi! 👋

The instructions on the website should probably be a bit more specific to make sure people do this correctly too.

I interpreted `Place this file in the ios/ directory of your project.` to mean that `cp ~/Downloads/GoogleService-Info.plist ios` would work. :)

**Comment by Salakar** [comment]
😫 you're right, looks like the starter guides are still a bit out of date, I did update the [main docs](https://rnfirebase.io/docs/v5.x.x/installation/ios#1.1.-Setup-GoogleService-Info.plist) a while back, guess I've missed this one, doh.

Have updated all the occurrences now; thank you for the feedback 🎉 

![image](https://user-images.githubusercontent.com/5347038/56074923-ed19db00-5db1-11e9-87d4-2b2796e9b482.png)

**Comment by TheSavior** [comment]
Ooh. That's much more clear. Nice. 👍
