### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.

### ISSUE THREAD

**Issue by NoR3s** [invertase/react-native-firebase-starter#113]
I have followed the tutorial but everytime i run my project i get this error "Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0."

**Comment by jbakchr** [comment]
I'm getting the same error ..

**Comment by mikehardy** [comment]
The starter packages gradle 4, so this is a warning not an error

If we shipped it with gradle 5 and were still using the features, that would be an error

So, this is fine and will be fixed prior to an upgrade

Note that react-native-firebase itself has no problem with gradle 5
