### ISSUE TITLE
when i clone the repo and rename the folder name it crashes ios

### ISSUE THREAD

**Issue by Monir-Shembesh** [invertase/react-native-firebase-starter#116]
exactly as the title says. when i clone the repo i get a folder named react-native-firebase-starter. the moment i rename this folder name the app crashes. I tried the rename function but it only renames the app.

**Comment by mikehardy** [comment]
I just followed the instructions in a clean directory and it works. I even made a pull request with all new versions, and it works. Can't reproduce https://github.com/invertase/react-native-firebase-starter/pull/118
