### ISSUE TITLE
Debugging throws error on Android because of Invites Package

### ISSUE THREAD

**Issue by Elbis** [invertase/react-native-firebase-starter#117]
I got compileDebugJavaWithJavac error  when i tried to start my project with react-native run-android. 

I deleted RNFirebase.Invites things and it works properly now.

May be a pull request need there.

**Comment by mikehardy** [comment]
well documented as part of the v5.5 release notes and messaged during each package install to raise awareness https://rnfirebase.io/docs/v5.x.x/releases/v5.5.x#Upgrade-instructions
