### ISSUE TITLE
Android application instantly crashes

### ISSUE THREAD

**Issue by ChristianTucker** [invertase/react-native-firebase-starter#12]
Instructions to replicate:   

1: Clone the latest build
2: yarn install
3: yarn run rename
4: manually rename rnfirebasestarter folder since rename doesn't do it
5: Add google-services.json
6: react-native run-android

Successful build -> App crashes

**Comment by Ehesp** [comment]
Can you share your Android logs? The crash will be explained in there.

**Comment by chrisbianca** [comment]
Closing due to lack of response - please re-open with your Android logs so we can help

**Comment by ilkome** [comment]
Same issue. Mac

01-20 21:03:03.403  5231  5231 D ReactNative: ReactInstanceManager.ctor()
01-20 21:03:03.450  5231  5231 D ReactNative: ReactInstanceManager.createReactContextInBackground()
01-20 21:03:03.450  5231  5231 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
01-20 21:03:03.451  5231  5231 D ReactNative: ReactInstanceManager.onJSBundleLoadedFromServer()
01-20 21:03:03.452  5231  5231 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
01-20 21:03:03.452  5231  5231 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
01-20 21:03:03.518  5231  5271 D ReactNative: ReactInstanceManager.createReactContext()
01-20 21:03:03.721  5231  5271 D ReactNative: Initializing React Xplat Bridge.
01-20 21:03:03.724  5231  5271 D ReactNative: Initializing React Xplat Bridge before initializeBridge
01-20 21:03:03.728  5231  5271 D ReactNative: Initializing React Xplat Bridge after initializeBridge
01-20 21:03:03.729  5231  5271 D ReactNative: CatalystInstanceImpl.runJSBundle()
01-20 21:03:03.731  5231  5289 D ReactNative: ReactInstanceManager.setupReactContext()
01-20 21:03:03.731  5231  5289 D ReactNative: CatalystInstanceImpl.initialize()
01-20 21:03:03.733  5231  5289 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
01-20 21:03:04.200  5231  5288 I ReactNativeJS: Running application "finapp" with appParams: {"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
01-20 21:03:05.089  5231  5231 D ReactNative: ReactInstanceManager.detachViewFromInstance()

**Comment by ilkome** [comment]
<img width="968" alt="screen shot 2018-01-20 at 21 04 56" src="https://user-images.githubusercontent.com/1069998/35186456-a145ed96-fe25-11e7-96cc-6fad882f00d3.png">

**Comment by ChristianTucker** [comment]
@chrisbianca Sorry, I've been super busy; My report looks exactly like @ilkome 's  There's no errors or crash messages. The app never even hits the "start-up" phase it seems. It crashes within half a second.

**Comment by hindsricardo** [comment]
I'm facing the same issue

**Comment by faddablack** [comment]
Facing the same issue as well

**Comment by mikehardy** [comment]
@faddablack can you confirm for me that you cloned recently (that is, `cat package.json |grep react-native` shows you that you have a dependency on react-native 0.60.5 - after we updated the starter in the last couple days) and also you'll need to check the results of `adb logcat` (maybe it's a missing admob id from AndroidManifest.xml or similar.

In general I'd recommend opening a new issue since this one is likely stale, but what I wrote here would apply in the new issue as well

**Comment by faddablack** [comment]
@mikehardy yes, I cloned today and I am on RN 0.60.5. I have removed  AdMob from AndroidManifest...

**Comment by faddablack** [comment]
@mikehardy problem was indeed the missing AdMob id. Much appreciate the help.

**Comment by mikehardy** [comment]
Glad that worked! Note that you can remove the AdMob dependency in build.gradle and Podfile if you don't want it - in the starter we just wanted to show it was possilbe
