### ISSUE TITLE
Can't run on Android

### ISSUE THREAD

**Issue by AndroidDoctorr** [invertase/react-native-firebase-starter#122]
I cloned the project as of 7/11/2019 and followed the instructions in the readme. I opened the Android project (/android) in Android Studio, ran "gradlew clean assembleRelease" in /android in the terminal, then built (Run 'app')
I've tried gradle versions 3.3.2 and 3.4.1, and in either case I get this when I try to run the app:
`Unable to load script. Make sure you're either running a Metro server (run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release`

I also tried version 3.1.4 and it fails to build:
`ERROR: Could not get unknown property 'mergeResourcesProvider' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl`

I've also tried creating an apk and copying it to my phone and installing it, but the installation fails.

How can I get this to run on my device via Android Studio? Is it only possible using an emulator?

**Comment by mikehardy** [comment]
So, did you try `react-native start` ? You should, in general, try a clean example pure react-native project prior to trying something advanced like react-native-firebase. So, my best advice is to follow the getting started guide from react-native main project

**Comment by AndroidDoctorr** [comment]
I already installed a pure react-native project, using 'react-native run-android' - using that here also produces the result mentioned above (Unable to load script...)

'react-native start' doesn't seem to accomplish anything. It says "Loading dependency graph, done." and then hangs

**Comment by AndroidDoctorr** [comment]
Why did you close the ticket?

**Comment by mikehardy** [comment]
I closed this because this react-native stuff, not react-native-firebase stuff. Do `react-native init testproject` and make that thing run. Once you see how it works (noting that running `react-native start` actually starts the metro packager, and it's there waiting to send the bundle over the network to your dev app on the emulator) then come back. If you can make an example project run but not the starter here, after following the instructions to the letter, we can reopen. But this appears to be about not understanding how react-native works, and that's not in the scope for a firebase module...

**Comment by AndroidDoctorr** [comment]
As I stated above, I've already successfully run several react-native projects. This one didn't work. But I found another react-native starter kit with firebase that worked the first time, so nevermind.

**Comment by mikehardy** [comment]
Ok, glad you found something that worked. If you are interested in a slightly different take on a starter you can try https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh as well

**Comment by mikehardy** [comment]
Just for grins, I had a minute and made sure I was clean on react-native-firebase-starter master. I did a yarn install, I did a yarn rename, moved my google-services json in place and a react-native run-android and it ran fine. I was pretty sure that was the case, but I wanted to make sure I had not in fact closed prematurely - I don't think I did. It appears to work fine for me ?

**Comment by AndroidDoctorr** [comment]
Yeah, actually I did the same, and it worked... My guess is I typed the package name wrong somewhere the first couple times? Not sure
