### ISSUE TITLE
NPM Install Error

### ISSUE THREAD

**Issue by DaSniper12** [invertase/react-native-firebase-starter#127]
Hi All,

I was planning to use this tool, but when I tried to install a basic starter kit, I ran into a problem again, after the cloning the repository, I ran npm install, and it got stuck with this, and it hasn't moved forward after an hour: npm WARN tarball tarball data for react-native@0.59.9 (sha512-/+8EgIZwFpYHyyJ7Zav7B6LHNrytwUQ+EKGT/QV7HSrgpf2Y5NZNeUYUHKiVKLYpBip1G32/LcAECQj37YRwGQ==) seems to be corrupted. Trying one more time.

I did it again, and I got the same error message, does anyone know what is wrong, and what I should do?

**Comment by mikehardy** [comment]
This sounds pretty odd - it appears you have an npm error. I recommend `npm i react-native-clean-project && react-native clean-project-auto` as a "big hammer" but maybe just an `npm cache verify` would do it. You can also try https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh or https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-rn59.sh for another take on starter construction but it'll probably have the same problem

**Comment by DaSniper12** [comment]
Do you recommend me doing that in the react-native-firebase-starter directory or the one outside it?

**Comment by DaSniper12** [comment]
That worked wonders, thanks for the help, I tried the first recommendation, and thats what did it, I look forward to using this, a lot so thanks for the help.
