### ISSUE TITLE
Getting ld: library not found for -lRCTGeolocation  error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by devika7** [invertase/react-native-firebase-starter#128]
Hi,

I have done all initial setup but while building my project in xcode, it fails and gives the error, IRCTGeolocation not found.

I tried following this step by step https://github.com/react-native-community/react-native-geolocation, still getting same error.

Please provide help.

**Comment by mikehardy** [comment]
geolocation library issue, not firebase-starter issue
