### ISSUE TITLE
Uncommenting pod 'Firebase/AdMob', '~> 6.3.0' causes failure

### ISSUE THREAD

**Issue by Jordan-Loeser** [invertase/react-native-firebase-starter#129]
Uncommenting the line`#pod 'Firebase/AdMob', '~> 6.3.0'` from the `Podfile` causes a white screen to appear after I run `pod install` and `npm run ios` on an app that previously worked. When I remove the dependency the starter app runs just fine.

**Comment by mikehardy** [comment]
If you'd look at the console output you'd probably notice it's a firebase crash because you didn't follow admob setup - it's more than just including the pod

https://rnfirebase.io/docs/v5.x.x/admob/ios#Update-your-plist-file

https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh#L113

Please read docs

**Comment by Jordan-Loeser** [comment]
Thank you! @mikehardy any tips for what I should look for in the console output to identify that in the future? In the iOS simulator system logs I'm not seeing firebase.

**Comment by Jordan-Loeser** [comment]
@mikehardy The app is compiling but I am still seeing `firebase.admob.nativeModuleExists` return false on the default starter app. Is there additional config that needs to be done other than registering for admob and adding the `GADApplicationIdentifier` to `Info.plist`?

**Comment by mikehardy** [comment]
No idea. Works for me fully automated like so - you can try it https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by mikehardy** [comment]
Oh - and I use Console.app to watch Simulator logs - it'll show you a selection of simulators or connected devices for your mac in the top left, then you can follow logs like that
