### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by IamMHC** [invertase/react-native-firebase-starter#130]
After Install React-Navigation this error occur 
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by mikehardy** [comment]
Sure would be great to see that compiler error output...

**Comment by IamMHC** [comment]
Now error has been change 
![err](https://user-images.githubusercontent.com/30019058/63641916-d4122680-c6cf-11e9-9cbb-351ca777f907.PNG)

**Comment by mikehardy** [comment]
You have a project-specific problem, it is not the problem of the firebase starter.

You have used jetifier it appears, but not actually done the AndroidX refactor in AndroidStudio, so you're not pulling in the correct library.

Troubleshooting AndroidX transitions in projects is outside the scope of this project - there are too many ways they can go wrong.

You can see a demo from scratch of react-native-firebase on both react-native 0.59 and 0.60 here though: https://github.com/mikehardy/rnfbdemo/ - use either make-demo.sh or make-demo-rn59.sh depending on what you want.
