### ISSUE TITLE
Dead link to new project guide

### ISSUE THREAD

**Issue by bobinrinder** [invertase/react-native-firebase-starter#145]
This is still the number one search result for `React Native Firebase boilerplate` but the link in the deprecation notice `DEPRECATED: This is for RNFB v5 only. For v6 onwards please follow the new projects guide.` is dead. 
Is there still a sample project? Wasn't there even an example project with some of the basic auth screens before? I think our company bought it a while ago but then it was free at some point as well I think. 
Would be a great thing to get people up and running quicker... Probably a lot to ask, but would be good to fix the message or the link at least. ✌️

**Comment by mikehardy** [comment]
I think this may just be a docs issue - there was a "template" which the react-native-cli can use to generate a boiler plate app but it is/was a maintenance burden and it's not that much easier than just following the docs

if you want to see a scripted version (with comments detailing exactly what's happening and why) that does the integration to a stock / vanilla react-native project you can try this: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh

**Comment by bobinrinder** [comment]
> I think this may just be a docs issue - there was a "template" which the react-native-cli can use to generate a boiler plate app but it is/was a maintenance burden and it's not that much easier than just following the docs

That's what I assumed. I do wish there would be a starter project that includes the basic screens, such a pain to always spend days building Login, Signup, Password forget, Verify, etc screens but I know it's a lot of work to get it going and maintain it. Maybe I'll give it a shot some day... 

In conclusion: The only easy thing for now could be fixing the dead link and maybe explain that following the docs is not much harder than using this starter project or at least just point it at the current `Getting Started` docs.

Just a suggestion... ✌️

**Comment by mikehardy** [comment]
@bobinrinder dos PRs are always happily accepted - every doc page has an edit link up top
I believe Invertase sells a starter pack for typical login flow etc, but there was never a demo that actually had the screens, all it did was just get everything installed and linked in
