### ISSUE TITLE
Adopt a create-react-app style?

### ISSUE THREAD

**Issue by ColinEberhardt** [invertase/react-native-firebase-starter#15]
Thanks for this starter project - it's really useful!

I was wondering whether it is possible or worth changing this project to adopt the same style as create-react-app, where the 'starter project' becomes an npm dependency rather than a seed for the project itself? This has some significant advantages for long term maintenance in that it is much easier to integrate changes and bug fixes from the seed project into your own.

**Comment by Ehesp** [comment]
Hey,

We have thought about this (more-so a larger CLI which does more than just create an app). I'll bring it up with the guys again. It's more just an investment of time which is the issue :D

**Comment by Salakar** [comment]
Huzzah! A CLI appeared: https://github.com/invertase/react-native-firebase-cli

This feature isn't on it yet - it's purely on Github to get contribs/help - see the readme.
