### ISSUE TITLE
React native packager error

### ISSUE THREAD

**Issue by Puetz** [invertase/react-native-firebase-starter#17]
Hi,
when I start the packager with `npm start` it says "Loading dependency graph, done" in the console but afterwards the following error message appears:

ERROR  EPERM: operation not permitted, lstat 'C:\Users\D067873\Git\Neu\react-native-firebase-starter\android\app\build\generated\res\google-services\debug'
npm ERR! code ELIFECYCLE
npm ERR! errno 11
npm ERR! phodl@0.1.0 start: `react-native start`
npm ERR! Exit status 11
npm ERR!
npm ERR! Failed at the phodl@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

The entire debug log looks like this:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\D067873\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle phodl@0.1.0\~prestart: phodl@0.1.0
6 info lifecycle phodl@0.1.0\~start: phodl@0.1.0
7 verbose lifecycle phodl@0.1.0\~start: unsafe-perm in lifecycle true
8 verbose lifecycle phodl@0.1.0\~start: PATH: C:\Users\D067873\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\D067873\Git\Neu\react-native-firebase-starter\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\ProgramData\Oracle\Java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\windows live\shared;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Java\jdk-9\bin;C:\Users\D067873\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\Cloud Foundry;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Users\D067873\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\D067873\apache-maven-3.5.2\bin;C:\Users\D067873\AppData\Roaming\npm\;C:\Users\D067873\AppData\Roaming\npm\node_modules\npm;C:\Program Files\Java\jre1.8.0_151\bin;C:\Program Files\PostgreSQL\10\bin;C:\Users\D067873\AppData\Local\Android\Sdk\tools;C:\Users\D067873\AppData\Local\Android\Sdk\platform-tools
9 verbose lifecycle phodl@0.1.0\~start: CWD: C:\Users\D067873\Git\Neu\react-native-firebase-starter
10 silly lifecycle phodl@0.1.0\~start: Args: [ '/d /s /c', 'react-native start' ]
11 silly lifecycle phodl@0.1.0\~start: Returned: code: 11  signal: null
12 info lifecycle phodl@0.1.0\~start: Failed to exec start script
13 verbose stack Error: phodl@0.1.0 start: `react-native start`
13 verbose stack Exit status 11
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\D067873\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\D067873\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid phodl@0.1.0
15 verbose cwd C:\Users\D067873\Git\Neu\react-native-firebase-starter
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\D067873\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.9.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 11
22 error phodl@0.1.0 start: `react-native start`
22 error Exit status 11
23 error Failed at the phodl@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 11, true ]

`Npm run android` returns "BUILD SUCCESSFUL" and my virtual device displays an error message saying "Unable to load script from assests 'index.andoird.bundle'. Make sure your bundle is packaged correctly or you're running a packager server."

After getting these errors for the first time, I cloned the repository again and tried everything again but I still get the error message. I did everything according to the "Getting Started" from the readme.md.
Thanks a lot for your help.

**Comment by Raammeena** [comment]
did complete the setup from firebase as it is explained,

**Comment by dillon** [comment]
I'm also having this issue. have tried seemingly everything: clearing cache, reinstalling watchman, reinstalling Pods files, restarting computer, etc.

**Comment by Salakar** [comment]
Please try the latest changes on master and if there's still an issue please re-create another GitHub issue with full details, thanks 👍 	

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by ashu2012** [comment]
is it resolved , still facing this issue
