### ISSUE TITLE
Android foreground notifications don't work out of the box

### ISSUE THREAD

**Issue by krozett** [invertase/react-native-firebase-starter#23]
iOS foreground and background notifications work fine. Android notifications would show for me in the background but not the foreground. They didn't even trigger the onMessage or onNotification handlers. I struggled for hours before realizing that there is some code that needs to be present in `android/app/src/main/AndroidManifest.xml`. Per these instructions (https://rnfirebase.io/docs/v4.0.x/messaging/android#Update-Android-Manifest):

```
  <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
    <intent-filter>
      <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
  </service>
  <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
    <intent-filter>
      <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
    </intent-filter>
  </service>
```

Once I added those lines, everything worked fine.

**Comment by Salakar** [comment]
Thanks for raising this, are you able to PR this if possible?
