### ISSUE TITLE
Build error on android

### ISSUE THREAD

**Issue by Rezania815** [invertase/react-native-firebase-starter#26]
### Issue

A problem occurred configuring root project 'RNFirebaseStarter'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find builder.jar (com.android.tools.build:builder:3.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.1.0/builder-3.1.0.jar

### Environment

1. Application Target Platform: Android

2. Development Operating System: Windows 10

**Comment by Salakar** [comment]
React Native Firebase v4.3.x support is now on master, which should cover this - will close this issue now. Thanks for the feedback.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
