### ISSUE TITLE
Error when run android

### ISSUE THREAD

**Issue by aalshaikh** [invertase/react-native-firebase-starter#29]
Hi,

when i run npm run android i git this error: 
com.android.build.api.transform.TransformException: Error while generating the main dex list.

and when i try it from Android Studio it's give me this error : 
Error:Program type already present: com.google.android.gms.internal.measurement.zzabo

**Comment by chrisbianca** [comment]
Please update to the latest code in the repo - this was a result of an update to Google's libraries which broke installation.  It's now resolved.
