### ISSUE TITLE
Firebase AUTH API to signInWithPhoneNumber is resulting in a 400 bad request

### ISSUE THREAD

**Issue by karthik1388** [invertase/react-native-firebase-starter#31]
Hi All,

I am using the basic firebase starter kit out on github to test out the firebase authentication piece. Below is the firebase starter kit link which walks through the steps to setup firebase with a basic react native application.

https://github.com/invertase/react-native-firebase-starter

The App.js has been replaced to have a very simple form that takes **phone number** as input and invokes the firebase auth API signInWithPhoneNumber(<phone-number>) to send out a text message. Below is the relevant code

1. Firebase intilization with all the relevant config details

    firebase.initializeApp({
      apiKey: '<API-KEY>',
      authDomain: '<>',
      databaseURL: '<>',
      projectId: '<>',
      storageBucket: '<>',
      messagingSenderId: '<>'
    });

2. Auth API call

firebase.auth().**signInWithPhoneNumber**(phoneNumber)
      .then(confirmResult => console.log(confirmResult))
      .catch(error => this.setState({message: `Sign In With Phone Number Error: ${error.message}`}));

This above API call(2) is resulting in a 400 bad request. A snapshot of the logs seen in the catlog is as below

**05-07 14:04:21.643  3509  6366 W FirebaseAuth: [PhoneVerificationSession] PhoneVerificationSession constructor
05-07 14:04:21.648  3509  4952 W FirebaseAuth: [PhoneNumberAuthPostProcessor] postProcess starts
05-07 14:04:22.284  3509 13712 E Volley  : [237] BasicNetwork.performRequest: **Unexpected response code 400 for https://www.googleapis.com/identitytoolkit/v3/relyingparty/sendVerificationCode?alt=proto&key=<API-KEY>**
05-07 14:04:22.286  3509  6366 W FirebaseAuth: [PhoneVerificationSession] onFailure
05-07 14:04:22.451  3509  4952 W FirebaseAuth: [PhoneNumberAuthPostProcessor] postProcess ends**

Not sure what the reason for the 400 bad request is. Any help would be highly appreciated.

Please let me know if any more information is needed to understand the issue.

**Comment by Salakar** [comment]
Please try the latest changes on master and if there's still an issue please re-create another GitHub issue with full details, thanks 👍 	

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
