### ISSUE TITLE
PNG file passed as argument. Must be compiled first into .flat file.. 

### ISSUE THREAD

**Issue by naody** [invertase/react-native-firebase-starter#32]
I'm getting the build error below when building my Android app on App Center. I was able to pass the build error by  adding `android.enableAapt2=false` to the `/android/gradle.properties`.  What's the ultimate solution? I believe this is a temporary fix?

```
:appcenter:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:react-native-firebase:generateReleaseRFile
Resolved com.facebook.react:react-native:0.55.4 in :react-native-firebase:releaseRuntimeClasspath 
Resolved com.android.support:support-v4:27.0.2 in :react-native-firebase:releaseRuntimeClasspath 
Resolved com.android.support:multidex:1.0.2 in :react-native-firebase:releaseRuntimeClasspath 
:app:processReleaseResources
/Users/vsts/agent/2.133.3/work/1/s/android/app/build/intermediates/res/merged/release/drawable-mdpi/assets_rnfirebase.png: error: uncompiled PNG file passed as argument. Must be compiled first into .flat file..
error: failed parsing overlays.
:app:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> Failed to process resources, see aapt output above for details.
```

My dependencies on `package.json` are the following:

```
  "dependencies": {
    "appcenter": "^1.5.0",
    "appcenter-analytics": "^1.5.0",
    "appcenter-crashes": "^1.5.0",
    "fbjs": "^0.8.16",
    "react": "^16.3.1",
    "react-native": "^0.55.3",
    "react-native-firebase": "^4.0.7"
  }
```

**Comment by Salakar** [comment]
Please try the latest changes on master and if there's still an issue please re-create another GitHub issue with full details, thanks 👍 	

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
