### ISSUE TITLE
IOS build - ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by sdb1228** [invertase/react-native-firebase-starter#35]
A copy to this:  https://github.com/invertase/react-native-firebase-starter/issues/33 if we want to reopen it that would be great otherwise here is my stack trace from the failed build.  

OS: 10.13.4
Node version: 8.2.1

```** BUILD FAILED **


The following build commands failed:

	CompileC /Users/stevenburnett/trackJess/react-native-firebase-starter/ios/build/Build/Intermediates.noindex/RNFirebase.build/Debug-iphonesimulator/RNFirebase.build/Objects-normal/x86_64/RNFirebaseFirestoreCollectionReference.o RNFirebase/firestore/RNFirebaseFirestoreCollectionReference.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/stevenburnett/trackJess/react-native-firebase-starter/ios/build/Build/Intermediates.noindex/RNFirebase.build/Debug-iphonesimulator/RNFirebase.build/Objects-normal/x86_64/RNFirebaseFirestoreDocumentReference.o RNFirebase/firestore/RNFirebaseFirestoreDocumentReference.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)

Installing build/Build/Products/Debug-iphonesimulator/trackJessSleep.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/trackJessSleep.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

**Comment by donszek** [comment]
@sdb1228 any progress to this? I encounter the same problem.

**Comment by nbatwara** [comment]
Same problem -- any solutions?

**Comment by mortenmo** [comment]
I fixed it by updating the FireCore version to 5.0.1 (in PodFile ..  'Firebase/Core', '~> 5.0.1'). It seems related to this issue on RNFirebase itself: https://github.com/invertase/react-native-firebase/issues/1110

**Comment by nbatwara** [comment]
@mortenmo you're a hero!

**Comment by sdb1228** [comment]
Sorry for no update on this.  I ended up just configuring firebase manually I will see if I can submit a pull request to fix this issue.

**Comment by sdb1228** [comment]
^ should hopefully fix your problems.  If not I would try to manually add firebase to your project rather than using the starter project.

**Comment by Rpaixao** [comment]
Cool!

**Comment by mowbell** [comment]
It's work for me:
In my project package.json had follow dependency:
```js
"react-native-firebase": "^4.0.0",
```
But, when i ran `yarn install`, I saw in `yarn.lock` after installation,  then was installed version 4.2.0

And  reviewing changelog
[https://github.com/invertase/react-native-firebase/releases]

4.2 supports v5+ of the Firebase iOS pods which contained a number of breaking changes"

the same for android

Then I updated `package.json` to:

```js
"react-native-firebase": "^4.0.3",
```
Maybe it is usefull to someone

**Comment by Salakar** [comment]
React Native Firebase v4.3.x support is now on master, which should cover this - will close this issue now. Thanks for the feedback.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by henrylearn2rock** [comment]
I followed the readme just now so my  git clone  should be master already.  I can see my `package.json` is using Firebase 5.3.0.  However I'm still getting the "Entry, ":CFBundleIdentifier", Does Not Exist" error.

> ** BUILD FAILED **
>
> ...
> 
> An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
> Failed to install the requested application
> The bundle identifier of the application could not be determined.
> Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
> Print: Entry, ":CFBundleIdentifier", Does Not Exist
> 
> Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/SeekThis.app/Info.plist
> Print: Entry, ":CFBundleIdentifier", Does Not Exist
> 
> 
> error Command failed with exit code 1.
>

**Comment by Salakar** [comment]
@henrylearn2rock also make sure you have added your Firebase google-services plist file in the correct place for iOS as per the readme - this error is common when the file isn't found

**Comment by michaelcavallaro03** [comment]
I have been struggling with this issue across multiple projects. After diving deeper into CocoaPods I found a solution that worked for me: 

1. `git clone https://github.com/invertase/react-native-firebase-starter`
2. `npm install`
3. `npm run rename`
4. `cd ios`
5. `pod repo update`
6. `pod install`
7. `cd ..`
8. Add Google-Info.plist to ios/
9. Add google-services.json to android/app
8. `npm run ios`

**Comment by vonkanehoffen** [comment]
I'm also having this problem. The above didn't work for me unfortunately. Things seem to be OK for the Android build though. I also had a similar, perhaps linked, issue to #68 that I got past using @zxonline's solution from that thread. Exact error when running `npm run rename` was: 
```
[replaceInFile] Error occurred:  { [Error: ENFILE: file table overflow, open './ios/Pods/Headers/Private/Protobuf/GPBExtensionInternals.h']
```
so I'm wondering if somehow that failure in `ios/Pods` screwed things up for me? (the suggested fix was to remove `Pods` so the `rename` would work, then `pods install` again afterwards. 

Alas, I'm still too much of a n00b on iOS stuff to properly diagnose. If I can give any further info to someone who can, I'm happy to though!

**Comment by anwarhamr** [comment]
Worked for me "Move your config file into the root of your Xcode project. If prompted, select to add the config file to all targets." after generating the googleservice.info.plist.  I had put mine in ios/projectName but moved it to ios/ and it's working.
