### ISSUE TITLE
Failed to Resolve

### ISSUE THREAD

**Issue by ifanfaizal** [invertase/react-native-firebase-starter#39]
I just starting to use this starter. After following all instructions, I got a gradle sync problems even though I didn't change any code/dependencies from the project. Here are some of the problems,

> Failed to resolve: multidex
> Failed to resolve: firebase-messaging
> Failed to resolve: support-fragment
> Failed to resolve: support-core-ui
> Failed to resolve: runtime
> Failed to resolve: common
> Failed to resolve: support-annotations

Please help me to solve this, thanks before :)

**Comment by Salakar** [comment]
React Native Firebase v4.3.x support is now on master, which should cover this - will close this issue now. Thanks for the feedback.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
