### ISSUE TITLE
google-service.json is missing

### ISSUE THREAD

**Issue by deepank411** [invertase/react-native-firebase-starter#4]
Hi,

I am trying to integrate firebase into my own project that I created using the ignite cli.

The error that I'm facing is

```
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /home/deepank/Downloads/PizzaApp/android/app/src/debug/google-services.json
  /home/deepank/Downloads/PizzaApp/android/app/google-services.json
```

The solution to this is to create the file from here: https://developers.google.com/mobile/add
But when I select my firebase project in the dropdown, it says "Visit the Firebase console to manage Google services for this project.", after which I am unable to find what should I do next.

Any kind of help or direction will be helpful.

**Comment by Salakar** [comment]
You need to follow the guide in the readme, it tells you how to set it up correctly.
