### ISSUE TITLE
Could not find method implementation() for arguments [com.google.firebase:firebase-messaging:17.0.0]

### ISSUE THREAD

**Issue by pedrozan** [invertase/react-native-firebase-starter#40]
When following the steps on the get started guide I get the following error:

    Could not find method implementation() for arguments [com.google.firebase:firebase-messaging:17.0.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

    npm -v
    5.6.0

Running on Ubuntu 18,04

Full output
```
npm run android --scan

> KleberApp@0.1.0 android /home/pedro/Documents/react-native-firebase-starter
> react-native run-android

Scanning folders for symlinks in /home/pedro/Documents/react-native-firebase-starter/node_modules (23ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* Where:
Build file '/home/pedro/Documents/react-native-firebase-starter/android/build.gradle' line: 15

* What went wrong:
A problem occurred evaluating root project 'KleberApp'.
> Could not find method implementation() for arguments [com.google.firebase:firebase-messaging:17.0.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

What can i do to fix this?

**Comment by Salakar** [comment]
React Native Firebase v4.3.x support is now on master, which should cover this - will close this issue now. Thanks for the feedback.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
