### ISSUE TITLE
is it possible to make app size smaller?

### ISSUE THREAD

**Issue by guitar9** [invertase/react-native-firebase-starter#43]
I only need Push Notification so I commented out the import statements, I dont use in MainApplication.java.
But it has still a size of 35,40 Mb, like befor comment out. Is it possible to make the app size smaller?

**Comment by u12206050** [comment]
We created a fully fledged app with various functionality such as firestore, messaging, storage analytics etc, and our app size is max 19 MB. I would suggest you take a look at the assets that you include in your app (images, fonts etc) these drastically increase the app size.
