### ISSUE TITLE
Android APP crash on release mode

### ISSUE THREAD

**Issue by sagark1510** [invertase/react-native-firebase-starter#45]
I can successfully build my app but as soon as I open it gets crashed. Debug mode works perfect, it's just release mode.

ADB Log shows below msg:
![screen shot 2018-07-27 at 5 33 47 pm](https://user-images.githubusercontent.com/2134076/43319835-d40da796-91c3-11e8-84d9-4fe9baacd33c.png)

Building show below logs:
![screen shot 2018-07-27 at 5 30 59 pm](https://user-images.githubusercontent.com/2134076/43319875-f24974ba-91c3-11e8-985f-297fb78891c6.png)

adb log says index.android.bundle is not packaged properly. How can I check that? What can be the issue? I can not understand. please guide me on this.

**Comment by Karthik-Bahiradhan** [comment]
I am also facing this issue. Can you please guide me on this

**Comment by sagark1510** [comment]
@Karthik-Bahiradhan run below command for now to generate android build.. 

`$react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res && react-native run-android --variant=release`

**Comment by g3yuri** [comment]
@sagark1510  i worked for me on mac

**Comment by sagark1510** [comment]
@g3yuri good to know that.

closing this issue.

**Comment by ARMATAV** [comment]
This is still an issue.

**Comment by dolphinflow86** [comment]
Still the same.

**Comment by l1br3** [comment]
update to RN 0.57 react 16.6.1 react-test-renderer 16.6.1 and it should work again.

**Comment by Ghuller** [comment]
Updating RN and React to their latest vertions (0.57.8 and 16.7.0, respectively) worked for me.

**Comment by motogod** [comment]
I get the issue now. I use admob in my project. Debug mode works very well, but released apk will crash.

react: 16.8.3
React native: 0.59.3
