### ISSUE TITLE
Failed to load bundle

### ISSUE THREAD

**Issue by Kingsta93** [invertase/react-native-firebase-starter#47]
Hi,

I have followed all the steps and upon completing the last step I am getting this error on iOS.
<img width="339" alt="screen shot 2018-08-01 at 21 15 52" src="https://user-images.githubusercontent.com/42009930/43546284-28989842-95d0-11e8-9bf8-248f76caf75f.png">

Any ideas?

**Comment by Saksham96** [comment]
I also came across the same error.
Can somebody come up with the solution?

**Comment by dillon** [comment]
I also came across this error when running `react-native run-ios` because my `npm start` stopped working

**Comment by dillon** [comment]
My error seems related. Been trying to fix for days.

`Loading dependency graph, done.
error: bundling failed: NotFoundError: Cannot find entry file index.ios.js in any of the roots: ["/Users/dillon/Dropbox/Code/Projects/monitor"]`

**Comment by aimeeroxanne** [comment]
Also having this issue: 
<img width="406" alt="screen shot 2018-09-11 at 2 12 13 pm" src="https://user-images.githubusercontent.com/30577166/45384941-b3d77d80-b5cc-11e8-9de5-c53bd50bd7c8.png">

**Comment by Eltute11** [comment]
I have the same problem :(

**Comment by morfsys** [comment]
Any updates? Fixes?

**Comment by rshdkhan** [comment]
same issue ,any one with solution ??
![screen shot 2018-10-05 at 10 59 14 pm](https://user-images.githubusercontent.com/24436164/46551873-52b47880-c8f2-11e8-98ee-ff7319b6113e.png)

**Comment by weitieda** [comment]
Same problem here...

**Comment by Salakar** [comment]
This should be fixed on master, please clone and try again, thanks 👍 	

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
