### ISSUE TITLE
You guys are ROCKSTARS

### ISSUE THREAD

**Issue by alimuqaddas** [invertase/react-native-firebase-starter#49]
I dont know how to send you guys a message that your starter kit and the package react-native-firebase is really a charm. I feel like i would have been dumped in a deep mess if you guys had not done this for community.
I wish (some day i will) to give you guys a heavy reward for this amazing effort. Thankssss A lootttt.

Lots of Love from PAKISTAN.

**Comment by Salakar** [comment]
@alimuqaddas thank you for the kind words, means a lot, we do try our best! 🤓
