### ISSUE TITLE
Build failed. Execution failed for task ':react-native-firebase:processDebugGoogleServices'

### ISSUE THREAD

**Issue by 0Fg** [invertase/react-native-firebase-starter#5]
Running with Android Studio I fail to build the app.
According to the [README](https://github.com/invertase/react-native-firebase-starter#2-add-google-services-files-plist--json) and according to [Google](https://firebase.google.com/docs/android/setup#manually_add_firebase) I used the [Firebase Assistant](https://developer.android.com/studio/write/firebase.html) to connect.
After connecting the build failed with the following error:
> Error:Execution failed for task ':react-native-firebase:processDebugGoogleServices'. Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.4.2.

**Comment by Ehesp** [comment]
Please follow the issue template, it's there to help us help you.

**Comment by brian1999lin** [comment]
I get this as well.

**Comment by morfsys** [comment]
Got the same error with following message:
No matching client found for package name 'com.invertase.rnfirebasestarter'

How do I change this package name to mine?

**Comment by PoojaVM** [comment]
I am also facing the same issue. Any solution available?

**Comment by pmdlt** [comment]
If you have this error, delete the "build" folder in "android/app/' then restart.
You can also apply the method described here if it works for you: https://stackoverflow.com/a/34834772

**Comment by Salakar** [comment]
React Native Firebase v4.3.x support is now on master, which should cover this - will close this issue now. Thanks for the feedback.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
