### ISSUE TITLE
Build fails when trying to run on Android.

### ISSUE THREAD

**Issue by ghost** [invertase/react-native-firebase-starter#52]
I am trying to run a starter on Android emulator by following the given instructions but I get an error: 

![screen shot 2018-09-06 at 21 19 50](https://user-images.githubusercontent.com/43045820/45177298-3fdb5500-b21b-11e8-8f30-74b4151c0ae1.png)

Any ideas why I'm getting this error?

**Comment by tohshine** [comment]
> hello ghost, put this line at the end of `android/app/build.gradle` file : 
> `com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true` 
> 
> then go to the `android` folder and do that: `./gradlew clean` 
> 
> after that in your root level project run that: `react-native run-android`

still the same issue

**Comment by emmadal** [comment]
i have fix it by this method:
 put this line at the end of ```android/app/build.gradle``` file : <br/> ```com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true``` <br/>
then go to the `android` folder and do that: ```./gradlew clean``` <br/>
after that in your root level project run that: ```react-native run-android```

**Comment by Salakar** [comment]
This should be fixed on master, please clone and try again, thanks 👍 	

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by emmadal** [comment]
💪💪💪
