### ISSUE TITLE
yarn install - lock error 

### ISSUE THREAD

**Issue by AleksanderDudek** [invertase/react-native-firebase-starter#53]
So I try and **yarn install** this **package.json**:

{
  "name": "CloudMsg",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "babel-jest": "23.4.0",
    "babel-preset-react-native-stage-0": "1.0.1",
    "fs-extra": "6.0.1",
    "jest": "23.4.0",
    "react-test-renderer": "16.4.1",
    "replace-in-file": "3.4.0"
  },
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "rename": "node ./bin/rename.js",
    "start": "react-native start",
    "test": "jest",
    "gradclean": "cd android && ./gradlew clean"
  },
  "jest": {
    "preset": "react-native"
  },
  "dependencies": {
    "fbjs": "0.8.17",
    "react": "16.3.2",
    "react-native": "0.55.3",
    "react-native-fbsdk": "0.7.0",
    "react-native-firebase": "4.3.6",
    "react-navigation": "2.7.0"
  }
}

-------------------------------------------------------------------------------
Output from **yarn install -- verbose** :
[errors.txt](https://github.com/invertase/react-native-firebase-starter/files/2364212/errors.txt)

I don't understand really what casues this lock/busy resource. Any chance one of you encountered such problem?

PS. Should I provide other files please give me a hint.

**Comment by Salakar** [comment]
I'd suggest closing Android Studio if you have it open between installs if this is happening - also make sure you haven't npm linked the main react-native-firebase project into the node_modules of the starter.
