### ISSUE TITLE
Update to v5.0.0

### ISSUE THREAD

**Issue by Salakar** [invertase/react-native-firebase-starter#57]
v5.0.0 RNFB has just landed - this needs updating to use that.

https://rnfirebase.io/docs/v5.x.x/release-notes

**Comment by kawashimaken** [comment]
https://github.com/invertase/react-native-firebase-starter/blob/c4840c0ec1a9f164c0ab14877879f5eba26e9198/.babelrc#L3

The latest release for this package (babel-preset-react-native-stage-0
) is April 2016 (almost 2.5 years ago)
When I try to upgrade manually myself, I have got the following errors

> Plugin/Preset files are not allowed to export objects, only functions.

I found this link, 
https://github.com/babel/babel/issues/6808#issuecomment-343792786

but I did have any luck to solve it.
Still looking for solutions...

**Comment by Salakar** [comment]
@kawashimaken that's because that preset no longer exists, it's now part of Metro (`metro-react-native-babel-preset`)

You can use our [/tests](https://github.com/invertase/react-native-firebase/tree/master/tests) app for an example v5 setup

**Comment by kawashimaken** [comment]
@Salakar Thank you for the info!
I will give it a try!

**Comment by IjzerenHein** [comment]
@kawashimaken @Salakar I pretty much have the starter working with RN-firebase v5 and RN v57. Was a bit of an hassle on the iOS side. Will push a PR for it later today

**Comment by IjzerenHein** [comment]
Fixed by PR #61

**Comment by Salakar** [comment]
This is now on master, thanks @IjzerenHein for the assist. Changes can be seen in #61 

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
