### ISSUE TITLE
Failed to notify dependency resolution listener.

### ISSUE THREAD

**Issue by emmadal** [invertase/react-native-firebase-starter#58]
Hello, i have some problems when i try to launch my app. i follow step by step the integration of `RNFB` in my app but when i compiled i found this error: <br/>
```FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify dependency resolution listener.
> The library com.google.android.gms:play-services-measurement-base is being requested by various other libraries at [[16.0.0,16.0.0]], but resolves to 16.0.2. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
> The library com.google.firebase:firebase-analytics is being requested by various other libraries at [[16.0.1,16.0.1]], but resolves to 16.0.3. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

````
this is my environement system : <br/>
``` React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      CPU: x64 Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
      Memory: 279.50 MB / 3.64 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.11.0 - /usr/bin/node
      Yarn: 1.10.1 - /usr/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.0 => 0.57.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-kill-packager: 1.0.0
```

**Comment by DatMoser** [comment]
Same Problem here!

**Comment by emmadal** [comment]
i have fix it by this method:
 put this line at the end of ```android/app/build.gradle``` file : <br/> ```com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true``` <br/>
then go to the `android` folder and do that: ```./gradlew clean``` <br/>
after that in your root level project run that: ```react-native run-android```

**Comment by Salakar** [comment]
This should be fixed on master, please clone and try again, thanks 👍 	

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
