### ISSUE TITLE
React-Native-Firebase-Starter

### ISSUE THREAD

**Issue by supergeekit** [invertase/react-native-firebase-starter#59]
Hi,

Is there are a plan to update the starter kit to v5.x.x ? If so when is it projected to happen?
I'm experiencing  bundling failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/rachelmoskowitz/Desktop/react-native-firebase-starter-master/node_modules/babel-preset-react-native-stage-0/decorator-support.js

which was created here : https://github.com/invertase/react-native-firebase/issues/1290

If not is there a run sheet or could you forward steps to upgrade the starter kit to v5.0.0?

Cheers,
Supergeek

**Comment by Salakar** [comment]
https://github.com/invertase/react-native-firebase-starter/issues/57
