### ISSUE TITLE
Idea - Implement wix's react-native-navigation

### ISSUE THREAD

**Issue by robinbeechey** [invertase/react-native-firebase-starter#6]
I've followed their setup but I am having trouble on android right now I think with the MainApplication class and its handling of packages.

[https://wix.github.io/react-native-navigation/#/](url)

**Comment by Ehesp** [comment]
This is out of the scope of this project. Wix totally override the way React Native works to provide their own navigation solution which introduces issues with other libs.

This project uses a JS based solution, you're free to swap in wixs nav library if you see it fit for your own project.
