### ISSUE TITLE
The application crashes when run on real android device

### ISSUE THREAD

**Issue by karim1999** [invertase/react-native-firebase-starter#60]
I have followed the instructions carefully, but the application does not run on a real device. It crashes as soon as I open it, although it is working just fine on the emulator.

**Comment by Salakar** [comment]
This should be fixed on master, please clone and try again, thanks 👍 	

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
