### ISSUE TITLE
Auth service with Starter project

### ISSUE THREAD

**Issue by alxizr** [invertase/react-native-firebase-starter#64]
Hi, 

i am using the starter project for a firebase authentication example project and once i am done with the importing of firebase and calling the "firebase.auth.signInWithEmailAndPassword(myEmail, myPassword)" method in a callback method assigned to a TouchableOpacity button i get an error message saying: 

undefined is not a function (evaluating "_reactNativeFirebase.default.auth.signInWithEmailAndPassword(myEmail, myPassword))

can you help ? thanks

**Comment by Salakar** [comment]
You're missing the brackets after `auth`, it should be `firebase.auth().signInWithEmailAndPassword(myEmail, myPassword)`

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
