### ISSUE TITLE
com.android.build.api.transform.TransformException: Error while generating the main dex list.

### ISSUE THREAD

**Issue by guitar9** [invertase/react-native-firebase-starter#66]
get error:

com.android.build.api.transform.TransformException: Error while generating the main dex list.

**Comment by l1br3** [comment]
Same here.

I just cloned the repo, made the rename, add the google-service and try to build a release

**Comment by wibb36** [comment]
I spent 5 hours with the same issue, Any news?

**Comment by Rohithgilla12** [comment]
Same problem, any solution?

**Comment by denizbas92** [comment]
==>> Add this code as shown below  inside android/app/build.gradle , it may works, But I am getting this error now while generating apk file ,I could not solve it yet.
defaultConfig {
    .....
    flavorDimensions "versionCode"
  }

productFlavors {
    // Define separate dev and prod product flavors.
    dev {
      minSdkVersion 18
      targetSdkVersion 26
    }
    prod {
      // The actual minSdkVersion for the application.
      minSdkVersion 18
      proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
      targetSdkVersion 26
    }
  }

**Comment by diazabdulm** [comment]
It's a problem with using NPM. Re-install the packages using Yarn

**Comment by mikehardy** [comment]
I believe this is a gradle cache issue actually

https://github.com/invertase/react-native-firebase/issues/1859#issuecomment-506624299
