### ISSUE TITLE
error on running rename

### ISSUE THREAD

**Issue by barjas** [invertase/react-native-firebase-starter#68]
after successful installation of the starter kit. when i run `npm run rename` then after i enter the company name, i get this error:
```
---------------------------------------
Updating project name: My Starter
---------------------------------------
[replaceInFile] Error occurred:  { [Error: ENFILE: file table overflow, open './ios/Pods/Protobuf/objectivec/GPBCodedInputStream_PackagePrivate.h']
  errno: -23,
  code: 'ENFILE',
  syscall: 'open',
  path:
   './ios/Pods/Protobuf/objectivec/GPBCodedInputStream_PackagePrivate.h' 
```
any idea?

**Comment by zxonline** [comment]
For temporaly solution:

- Remove "Pods" folder in "ios".

- Run npm run rename

- Then back to 1.4 ( cd ios and run pod install )

**Comment by barjas** [comment]
@zxonline  . i tried that .. didnt work. 
After restarting the mac, every thing worked magically!!
