### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by RyanSalih** [invertase/react-native-firebase-starter#69]
when i compile the starter kit, it show this : 

Could not resolve all files for configuration ':react-native-firebase:debugCompileClasspath'.
> Could not find play-services-basement.aar (com.google.android.gms:play-services-basement:15.0.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.1/play-services-basement-15.0.1.aar

**Comment by SputnikTee** [comment]
I had the same problem today.
[This answer](https://stackoverflow.com/a/51213879/10518228)  on StackOverflow worked out for me.

Just put the `jcenter()` at the end of the 'repositories' lists in the android/build.gradle.

**Comment by RyanSalih** [comment]
`jcenter() ` is already there. still the problem is not solved.

**Comment by ggdegreat** [comment]
doesn't work

**Comment by mikehardy** [comment]
The old version should have worked, nevertheless I have a pull request out for the most current version and it worked for me https://github.com/invertase/react-native-firebase-starter/pull/118
