### ISSUE TITLE
Gradle can't sync on a fresh install

### ISSUE THREAD

**Issue by pedromrb** [invertase/react-native-firebase-starter#70]
Hi, on a fresh install and after following the steps required from the docs: 

https://rnfirebase.io/docs/v5.x.x/installation/basic-kit

on opening the folder android on Android Studio, Gradle can't sync out of the box.
To my understanding it's due on having the `google-services` instance, `google()` after the `jcenter()` invocation.

So my fix was just doing this:
```js
google()
jcenter()
```

If it makes sense i can make a PR with this minor change.

Thanks

**Comment by Clausinho** [comment]
same issue, would love a PR to fix this

**Comment by Salakar** [comment]
Hey, I've changed this on https://github.com/invertase/react-native-firebase-starter/pull/74

Thanks for the report. 👍 

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
