### ISSUE TITLE
app crashes immediately after launching on ios simulator

### ISSUE THREAD

**Issue by lfeddern** [invertase/react-native-firebase-starter#71]
Have battled with this for quite a few hours but can't install for ios (haven't tried for android).

The project builds successfully, but on the ios simulator the app opens before immediately crashing and closing again.

I had the same problem when trying to add to a preexisting project so tried with the starter project with no avail. 

Reading the docs it states this can happen if GoogleService-Info.plist isn't registered but I have added it as described to the ios folder, and it is visible on XCode also.

<img width="260" alt="screen shot 2018-10-28 at 17 25 11" src="https://user-images.githubusercontent.com/10187990/47619443-85f3bd00-dad6-11e8-9462-adae29e01db6.png">

<img width="276" alt="screen shot 2018-10-28 at 17 25 28" src="https://user-images.githubusercontent.com/10187990/47619442-85f3bd00-dad6-11e8-9e9e-101413657c91.png">

And the bundle id from the build lines up with that from the GoogleService-Info file:
<img width="846" alt="screen shot 2018-10-28 at 17 30 21" src="https://user-images.githubusercontent.com/10187990/47619522-893b7880-dad7-11e8-9fc3-5ac24f798348.png">

Bundle id in GoogleService-Info:

<img width="796" alt="screen shot 2018-10-28 at 17 31 05" src="https://user-images.githubusercontent.com/10187990/47619524-8c366900-dad7-11e8-9117-0a36767b0209.png">

The simulator system log looks like this right when it crashes:
<img width="659" alt="screen shot 2018-10-28 at 17 49 38" src="https://user-images.githubusercontent.com/10187990/47619743-eb957880-dad9-11e8-852a-2fdbd17ff5ca.png">

And the bundler looks like this:
<img width="572" alt="screen shot 2018-10-28 at 17 48 48" src="https://user-images.githubusercontent.com/10187990/47619761-12ec4580-dada-11e8-89fc-fc9d79ce8d12.png">

Any help would be greatly appeciated!! Really want to get this working.

Thanks in advance!.

**Comment by ecompton3** [comment]
I'm seeing this issue as well. Would really like to upgrade to the new firebase versions

**Comment by lfeddern** [comment]
Building through Xcode I see the error: 
*** Terminating app due to uncaught exception 'FIRAnalyticsVersionMismatch', reason: 'Google Analytics for Firebase version (50200000) does not match with Google App Measurement (50300000) version. Please update.'"

**Comment by ecompton3** [comment]
Looks like it's related to this issue https://github.com/invertase/react-native-firebase/issues/1633 doing the fix there worked for me

**Comment by lfeddern** [comment]
Yes I saw that! Trying to fix, would you be able to screen shot your Podfile? 
Do you then:
pod update 
pod install

To fix?

**Comment by lfeddern** [comment]
For anyone else that has this problem:
Podfile
<img width="634" alt="screen shot 2018-10-28 at 20 50 41" src="https://user-images.githubusercontent.com/10187990/47621674-32dc3300-daf3-11e8-9037-203abf212c4b.png">

`pod update`
`pod install`
