### ISSUE TITLE
npm run rename only works once

### ISSUE THREAD

**Issue by Clausinho** [invertase/react-native-firebase-starter#75]
Basically the title explains it all, after running the npm script it does not work anymore.

Best solution would be to code the ability to still change the project name, even if it was changed already.

A slightly less intensive solution would be to add a check, if the project was already renamed and thus can't be renamed again, instead of falsely outputting that the parameters were changed.

Below is the output after running `npm run rename` for a second time:
```

---------------------------------------------------------
Enter your Project name, e.g. My Amazing Project: boozr
---------------------------------------------------------
Enter your Company name, e.g. My Company: boozr
---------------------------------------------------------
---------------------------------------
Updating project name: boozr
---------------------------------------
[replaceInFile] Modified files:

---------------------------------------
Finished updating project name
---------------------------------------

---------------------------------------
Updating package name: com.boozr.boozr
---------------------------------------
[replaceInFile] Modified files:

---------------------------------------
Finished updating package name
---------------------------------------

---------------------------------------
Rename project files
---------------------------------------
---------------------------------------
Finished renaming project files
---------------------------------------

---------------------------------------
Rename company files
---------------------------------------
---------------------------------------
Finished renaming company files
---------------------------------------


---------------------------------------------------------
Set project parameters to:
---------------------------------------------------------
Project name:  boozr
Company name:  boozr
Package name:  com.boozr.boozr
---------------------------------------------------------
```

**Comment by Clausinho** [comment]
A temporary solution would be to run `git reset --hard` and then running `npm run rename` with the right parameters again

**Comment by Salakar** [comment]
@Clausinho thanks for this. Ideally I'd like to move all this functionality into our upcoming CLI, see: https://github.com/invertase/react-native-firebase-cli

**Comment by Clausinho** [comment]
interesting, thanks for pointing me into that direction.
If I find time I might even try to submit a PR for that.

**Comment by infinitey** [comment]
> git reset --hard && git clean -ifdx && npm install && npm run rename
does not work. Are there any other solutions? Thanks
