### ISSUE TITLE
app crashes on android 4.4 when building release and installing on a real device

### ISSUE THREAD

**Issue by afrakhan123** [invertase/react-native-firebase-starter#81]
Crashes on app launch on device, but works fine in debug mode on device and on simulator.

Already followed the steps to enable multidex:

public class MainApplication extends MultiDexApplication implements ReactApplication {...}

dependencies {...
  implementation 'com.android.support:multidex:1.0.3'
}

manifest:
      android:name=".MainApplication"

**Comment by afrakhan123** [comment]
getting the following in release mode:

11-24 01:29:53.611 30056-30099/? E/AndroidRuntime: FATAL EXCEPTION: Thread-9
    Process: com.pu.posfire, PID: 30056
    java.lang.RuntimeException: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
        at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
        at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:216)
        at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:32)
        at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:243)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1114)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:116)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:913)
        at java.lang.Thread.run(Thread.java:764)

**Comment by afrakhan123** [comment]
can someone please help it's urgent

**Comment by Salakar** [comment]
Hey, @afrakhan123 , seems like a weird issue in that it can't find your JS bundle - might not be related to the library but can you create an issue over here: https://github.com/invertase/react-native-firebase/issues/new?template=Bug_report.md

Please fill out all the information :) (to give me something to go by when reviewing your issue) - tag me in the new issue as well please.

I can take a look at it once I get home tonight, most likely tomorrow though.

Thanks

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by l1br3** [comment]
@afrakhan123 I get exactly the same problem, did you manage to solve your issue ?

**Comment by l1br3** [comment]
Seems to be an issue with gradle 3.2

https://github.com/facebook/react-native/issues/21132

**Comment by l1br3** [comment]
Updating to RN 0.57.7 fixed the issue for me without need of hacking react native react.gradle
