### ISSUE TITLE
RNFirebase core module was not found in Sample Project

### ISSUE THREAD

**Issue by wmonecke** [invertase/react-native-firebase-starter#84]
````
RNFirebase core module was not found natively on iOS, ensure you have correctly included the RNFirebase pod in your projects `Podfile` and have run `pod install`.
````

If you run the sample project you get the mentioned error. I dont understand what is going with RNFirebase but I did the manual integration and after receiving the `import FirebaseCore.h` error multiple times I decided to just use the sample project. Now this.

Also the pod `Firebase/Core` is declared twice in the podfile.

Once in required by RNFirebase and another time in the optional Pods.

**Comment by tevonsb** [comment]
I have the same issue.

**Comment by ashwath20** [comment]
i am also facing the same issue

**Comment by matthieunelmes** [comment]
I managed to fix with a bit of trial and error with a combination of the following:

run `pod update` then `pod install` in the ios directory

run `react-native link` - This was a suggestion from the react-native GITHub

Not entirely sure which of these fixed the issue for me, but it works now.

**Comment by anna-vasilko** [comment]
"pod update" fixed it for me
