### ISSUE TITLE
"yarn run start" hanging at "Loading dependency graph, done."

### ISSUE THREAD

**Issue by elimydlarz** [invertase/react-native-firebase-starter#85]
I was excited to see that https://github.com/invertase/react-native-firebase-starter/issues/51 had been resolved and started a new project as per `README.md`, but I still have the same problem.

I was very careful here - cloned the repo, clean installation of the latest Yarn, Node and CocoaPods before starting. When I first experienced this issue in late September I was able to start a new vanilla React Native project without difficulty.

Are others still experiencing this issue? It was closed before anybody was able to try the newest version and report back.

```
xxx:react-native-firebase-starter xxx$ yarn run start
yarn run v1.12.3
$ react-native start
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /Users/xxx/xxx/xxx/react-native-firebase-starter

Loading dependency graph, done.
```

**Comment by Ehesp** [comment]
Isn't this normal behaviour? Have you tried loading up the app, it should connect to the bundler now.

**Comment by elimydlarz** [comment]
I think normally it would eventually stop hanging and start the app, right?

`yarn run ios` works (after some fiddling, because I use NVM).

**Comment by Ehesp** [comment]
The start command just starts a local webserver using metro to server the JS assests, you need to use the run command to start your app on the emulator, which then connects to the webserver.

**Comment by jmargolisvt** [comment]
> The start command just starts a local webserver using metro to server the JS assests, you need to use the run command to start your app on the emulator, which then connects to the webserver.

I think this should be made explicit in the docs.
