### ISSUE TITLE
npm run rename 

### ISSUE THREAD

**Issue by austinwalker** [invertase/react-native-firebase-starter#86]
Hi.

First off, thank you for making and supporting this project. It's been immensely helpful. 

I am trying to rename my app after working on it for several months. It seems the `npm run rename` tracks down all the spots it needs to change but I get an error (below). 

I've run `npm install` and `yarn install`.
I'm on node v9.8.0, Mac Mojave 10.14.1.

Any thoughts?

```
---------------------------------------
Rename project files
---------------------------------------
(node:26195) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat './/node_modules/node-pre-gyp/node_modules/.bin/detect-libc'
    at Object.fs.statSync (fs.js:972:11)
    at Object.statSync (/Users/austinwalker/Sites/prayer-app/node_modules/graceful-fs/polyfills.js:295:24)
    at renameFiles (/Users/austinwalker/Sites/prayer-app/bin/rename.js:54:25)
    at renameFiles (/Users/austinwalker/Sites/prayer-app/bin/rename.js:63:13)
    at renameFiles (/Users/austinwalker/Sites/prayer-app/bin/rename.js:63:13)
    at renameFiles (/Users/austinwalker/Sites/prayer-app/bin/rename.js:63:13)
    at renameFiles (/Users/austinwalker/Sites/prayer-app/bin/rename.js:63:13)
    at Promise (/Users/austinwalker/Sites/prayer-app/bin/rename.js:99:9)
    at new Promise (<anonymous>)
    at renameProjectFiles (/Users/austinwalker/Sites/prayer-app/bin/rename.js:98:12)
(node:26195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:26195) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dmamaril** [comment]
Delete ios/Pods, run `npm run rename` and re-install your pods

**Comment by karenerobinson** [comment]
This is great!  The README should be changed so that it says to do 'npm run rename' before doing 'cd ios; pod install'

**Comment by mikehardy** [comment]
> should be changed

A good idea - make a PR :-), you can do it right in the GitHub UI for docs stuff normally, and you get valuable internet points for contributing 💪

**Comment by devika7** [comment]
Hi, I am still getting this error. Is there any fix for the command?

**Comment by mikehardy** [comment]
strange I just merged a PR to the docs for this this afternoon I believe

You might try this though, it's what I do on osx

https://github.com/mikehardy/rn-androidx-demo/blob/master/make-demo.sh#L12

**Comment by devika7** [comment]
Thanks! :)  I found a quick fix to it by running npm install again, and did audit fix on it. and it started working.
