### ISSUE TITLE
After setup, getting error: RNFirebase core module was not found natively on iOS

### ISSUE THREAD

**Issue by tevonsb** [invertase/react-native-firebase-starter#87]
After going through the whole setup process I get the error: 

`RNFirebase core module was not found natively on iOS, ensure you have correctly included the RNFirebase pod in your projects `Podfile` and have run `pod install`.

 See http://invertase.link/ios for the ios setup guide.

Firebase
    firebase.js:28:22
<unknown>
    firebase.js:97:20
loadModuleImplementation
    require.js:292:12
<unknown>
    index.js:1
loadModuleImplementation
    require.js:292:12
<unknown>
    App.js:4
loadModuleImplementation
    require.js:292:12
<unknown>
    index.js:4
loadModuleImplementation
    require.js:292:12
guardedLoadModule
    require.js:179:45
global code
    <unknown file>:0`

I haven't made any modifications to the files. Just `npm install`, `pod install`, and adding the `GoogleService-info.list` to the application through XCode.

Has anyone else found a solution to this issue?

**Comment by Ehesp** [comment]
Please follow the issue template with versions, code from files etc.
