### ISSUE TITLE
`npm run rename` doesn't rename project directory in Android subtree

### ISSUE THREAD

**Issue by divad12** [invertase/react-native-firebase-starter#9]
1. Follow the instructions in the README up to the step that runs `npm run rename`.
2. Run `cd ./android/app/src/main/java/com/<company name> && ls`
3. ... get the output: `rnfirebasestarter`, whereas we'd expect `<project name>`

Tested on [this commit](https://github.com/invertase/react-native-firebase-starter/tree/9f46f0eb31ff50cf2a44343e347a7b600c30a038) of RNFirebaseStarter.

**Comment by chrisbianca** [comment]
Fixed via: #22f373349be9a953828f7e0e4e8f4fe5b8626491

**Comment by ibu2710** [comment]
it is not renaming in ios directory

only android is renaming

**Comment by Warmachine13** [comment]
how to run this in the ios ???

**Comment by Warmachine13** [comment]
<html> <p>Please help i need to run react native firebase starter</p></html>

**Comment by pavsoor** [comment]
I came across this issue. Fixed it by:

1) npm install (installs dependencies)
2) npm audit fix (if you get a warning saying there are vulnerabilities - which I did!)
3) npm run rename

**Comment by iboxgithub** [comment]
I tried @pavsoor solution but it still doesn't work, I have this message:
npm ERR! missing script: rename

Which is weird cause it works on other projects...

**Comment by mikehardy** [comment]
@iboxgithub with apologies for being blunt, but you're doing something fundamentally wrong - 'rename' is a package.json script https://github.com/invertase/react-native-firebase-starter/blob/master/package.json#L10 so it will always work if you are calling it in the correct directory per the instructions

**Comment by iboxgithub** [comment]
My apologies, that was not an answer for this thread...thanks for pointing it out @mikehardy 
I will delete my post soon to not pollute the thread
