### ISSUE TITLE
`react-native link` breaks app

### ISSUE THREAD

**Issue by samcorcos** [invertase/react-native-firebase-starter#93]
I've been troubleshooting this for some time. I have two apps that are built on top of this project (thanks so much for that, by the way!!) and they both have the same problem. The issue is that whenever I add a new package that requires `react-native link`, the app no longer works after clear `node_modules` and `ios/build`. 

I'm not sure how consistent the errors are, but among them are:

```
** BUILD FAILED **

The following commands produced analyzer issues:
	Analyze Base/RCTModuleMethod.mm normal x86_64
	Analyze RCTImageCache.m normal x86_64
	Analyze RCTNetInfo.m normal x86_64
(3 commands with analyzer issues)

The following build commands failed:
	CompileC /Users/xxxx/code/placement/placement-mobile/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNGestureHandler.build/Objects-normal/x86_64/RNGestureHandlerModule.o /Users/xxxx/code/placement/placement-mobile/node_modules/react-native-gesture-handler/ios/RNGestureHandlerModule.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

```
Loading dependency graph...(node:70470) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: react-native
  Paths: /Users/xxxx/code/placement/placement-mobile/ios/Pods/React/package.json collides with /Users/xxxx/code/placement/placement-mobile/node_modules/react-native/package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (/Users/xxxx/code/placement/placement-mobile/node_modules/jest-haste-map/build/index.js:569:17)
    at workerReply (/Users/xxxx/code/placement/placement-mobile/node_modules/jest-haste-map/build/index.js:641:9)
```

I'm able to replicate this fairly easily, so I'm surprised this hasn't come up as an issue before (or at least not as far as I can tell). Here's a minimum reproducible bug, in which I followed the instructions to download and run, then I installed `react-navigation` and followed the [installation instructions in their README](https://reactnavigation.org/docs/en/getting-started.html), which includes a `react-native link`. Then, to replicate someone else cloning this, I delete `node_modules` and `ios/build` and run:

https://github.com/samcorcos/react-native-firebase-starter-bug

```
npm i
cd ios
pod install
cd ..
npm run ios
```

...and then I get the errors that you'll see if you run it yourself.

Fortunately, there is a workaround, which is to simply never use `react-native link` and to manually install everything for iOS. This is what I have in my project documentation and it does the trick, but still feels weird to have to do this:

```md
Open `<project>.xcodeworkspace`, right click on `Libraries` and click `Add Files to Candor`. Look under `node_modules/<the package in question>` and add `*.xcodeproj`. Then go to `Build Phases` and select `Link with Binaries`, and select the `*.a` file from within the directory you just added within `Libraries` and drag it into the list. And anything that gets added to the `Podfile` needs to be removed or commented out (e.g. `  # pod 'RNFS', :path => '../node_modules/react-native-fs'`) or the app wont work after a clean install and build.
```

**Comment by jearaneda** [comment]
I have the exact same problem. I'm able to get the example up and running, but installing anything else (e.g. react-navigation) and proceeding with react-native link breaks the application

**Comment by samcorcos** [comment]
I'm going to go ahead and close this since it looks like the underlying package is moving from 5.x => 6.x and this will no longer be relevant at that point.
