### ISSUE TITLE
Unhandled JS Exception: Unexpected token '{'. import call expects exactly one argument.

### ISSUE THREAD

**Issue by CyrusZei** [invertase/react-native-firebase-starter#98]
I just made a clean install from this repo and as soon as I run

1.yarn start
2.yarn run ios

I get this red error saying 

`
     
    Unhandled JS Exception: Unexpected token '{'. import call expects exactly one argument.

    no stack

`

Anybody else having this problem ?

**Comment by CyrusZei** [comment]
no idea what happend, I just restared my computer and now stuffs work.

**Comment by tinmar33** [comment]
> no idea what happend, I just restared my computer and now stuffs work.

It works for me as well
