### ISSUE TITLE
Error while merging dex archives (Android)

### ISSUE THREAD

**Issue by LeviWilliams** [invertase/react-native-firebase-starter#99]
Everything on the iOS side works perfectly for my app. Whenever I run it on android I get the following error. I have no clue why this is happening and I have scoured this repo as well as the main react-native-firebase repo and I cannot find any solutions that have helped the problem.

![Error](https://i.ibb.co/LdtJLc6/Screen-Shot-2019-03-08-at-12-45-58-PM.png)

**Comment by IanArko** [comment]
If anybody needs the answer still, find the answer here:

https://github.com/invertase/react-native-firebase/issues/1836
